### ISSUE TITLE
checklist for prototype

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/vca-collect-website#1]
- [x] support upload of both VCAs and PoAs linked to a single community
- [x] multi-language support for country dropdown
    - [x] can be hard to find country you want, provide search box
- [ ] ~search functionality on "Find" page~
- [x] grid/card view for documents on "Find" page
- [x] content for "About" page
- [x] summary stats for "About" page 
- [ ] branding and acknowledgment
- [ ] social share options (FB and Twitter)
- [x] pick and implement consistent style/theme/color  
- [x] automated, regular backup process to save copy of db containing document metadata to S3
- [ ] changing of filenames
- [x] move "deleted" files to separate S3 folder, save a text file alongside with metadata at time of deletion
- [x] trim title, filename, and description in admin documents table for more compact display (then show full description in the open edit modal)
- [x] allow edit of user passwords
- [ ] get translations
- [x] allow edit of community name

**Comment by danbjoseph** [comment]
## Feedback from IFRC
### Home Page:
- When moving the cursor on this page, a list of countries seems to be dragged along.
    - probably an Internet Explorer issue? what browser and version are they using?
- Some other key VCA resources , such as the ‘Integrating climate change and urban risks’ and ‘VCA: Lessons Learned and Recommendations’ could be added.
    - sure, just need the links and where they want them included
- Agree that it would be helpful to add some summary statistics here, either on the use of VCA in the different regions (percentages) or the number of VCAs included in the repository.
- Would suggest to use both the IFRC and GDPC logo (but would need to take this up with legal)
    - awaiting additional guidance
- Not sure about Twitter or Facebook share options (would need to ask our comms people) but using the Cash website example seems to be great idea.
    - awaiting additional guidance
- Need to also have the site over time in the 4 IFRC languages, especially for the sharing option, or only in English?
   - site is setup for this, just need the translations once content is finalized
### Find:
- Would you also be able to find the VCAs/POAs by clicking on the country in the Homepage?
    - could potentially add a map on the `/find` page but because there is no link or URL to get to the documents list for a particular country (it is all through interacting with and manipulating the `/find` page once it loads) i cannot link from the map on the home page to a list of documents for a particular country on the find page
- No functional links to VCA documents yet?
    - i have not added any actual documents to the website, the database design and metadata for the docs should be finalized first
### Share:
- Not sure we will be able to come up with a list of communities from which to select.
    - communities have to be added manually, but once a community has been added to a particular country, it will be available in the dropdown as an option for all future submissions
- Have a maximum of words for the description (200)
    - it is easy to limit the character length of the text input field. i don't know of an easy way to limit by word count.
- Mention the language the document is in.
   - this can be added as an additional dropdown field on the share form
- Would it be an option to add the Geographical References (maybe something the intern could do for the already existing ones?), so that the location can be found on a country map?.
    - how would the user input this? zooming to a location on a map and clicking to add a point?
- Not sure that VCAs and PoAs are always separate documents . Should there be an option for VCA/PoA?
    - this complicates search and stats and the database design. but needs to be considered if this is the case.
- Is it still possible to include a tab for Case Studies? In the VCA sharepoint library there are a few case studies that would be good to include here.
    - does this need to be a separate tab or can it be a section block on the home page?
